### ISSUE TITLE
Please improve the module

### ISSUE THREAD

**Issue by paulgeisler** [gerasimvol/vue-faq-accordion#1]
You did a great job, i really like it!

But it's still sketchy as a npm module. There is no real implementation, no how-to. You will get way more attention by improving this stuff. ;)

Thanks for the good vue component!

**Comment by gerasimvol** [comment]
thanks for your comment! i'll try my best to do it, but currently I have no idea how to make it :(

**Comment by gerasimvol** [comment]
@paulgeisler done 🤗
https://www.npmjs.com/package/vue-faq-accordion
now working on README but you already can install via `npm i vue-faq-accordion` and use it 😉

**Comment by paulgeisler** [comment]
Awesome! The downloads are increasing since then. 👍

**Comment by gerasimvol** [comment]
@paulgeisler yeah, thanks for pushing me forward 😊
