### ISSUE TITLE
Some way to control  activeTab and activeQuestionIndex

### ISSUE THREAD

**Issue by atulshukla** [gerasimvol/vue-faq-accordion#14]
How can i set  view to a particular tab and question when rendered.

I would like to control what tab and questions are shown via some props. changing those props should update the view.

**Comment by gerasimvol** [comment]
Added props for you:
```js
/**
 * Opened by default tabName (category)
 */
initialTab: {
  type: String,
  default: null
},
/**
 * Opened by default question
 * All closed by default
 */
initialQuestionIndex: {
  type: Number,
  default: null
}
```
Check demo: https://github.com/gerasimvol/vue-faq-accordion/blob/master/demo/src/App.vue#L25
