### ISSUE TITLE
Component props ??

### ISSUE THREAD

**Issue by ghost** [gerasimvol/vue-faq-accordion#17]
Hi, thank you for this awesome vue-faq-accordion.

Is it possible to pass a list of components as properties?

Example:

`export default {
  components: {
    VueFaqAccordion
  },
  data () {
    return {
      myItems: [
          {
            title: 'Title for a Component content',
            component: 'MyComponent1',
            category: 'Tab-1'
          },
          {
            title: 'Title for a Component content',
            component: 'MyComponent2',
            category: 'Tab-1'
          },
          {
            title: 'Title for a Component content',
            component: 'MyComponent3',
            category: 'Tab-2'
          },
          {
            title: 'Title for a Component content',
            component: 'MyComponent4',
            category: 'Tab-2'
          }
        ]
    }
  }
}`

I think this component can be used for more things besides the frequently asked questions.

**Comment by gerasimvol** [comment]
use slots
