### ISSUE TITLE
Initial question index doesn't work when value is 0

### ISSUE THREAD

**Issue by nsuaifan** [gerasimvol/vue-faq-accordion#20]
First of all, thanks for this component, it's awesome!

I want to default open the first question in my tab. initialTab prop works fine, and initialQuestionIndex mostly works, EXCEPT when initialQuestionIndex = 0. In this case, nothing opens by default - expected behavior is the first question opens.

**Comment by gerasimvol** [comment]
Hi. Can you provide reproduction demo or video with bug? `:initialQuestionIndex="0"` works for me.
