### ISSUE TITLE
Style Title and value

### ISSUE THREAD

**Issue by nero2009** [gerasimvol/vue-faq-accordion#4]
Awesome library here. I am currently using this library in an application I am working on, please is it possible to style the title and values? like font-size, font-weight e.t.c

**Comment by ihojmanb** [comment]
> Awesome library here. I am currently using this library in an application I am working on, please is it possible to style the title and values? like font-size, font-weight e.t.c

Yes you can, just inspect it and override the class attributes. If your style block is scoped, add another style block without the scoped property and put your code there if you want to see changes.

**Comment by gerasimvol** [comment]
@nero2009 thanks for using ✌️
similar question here #3
