### ISSUE TITLE
integrate medias / component 

### ISSUE THREAD

**Issue by tpoussard** [gerasimvol/vue-faq-accordion#9]
Hye gerasimvol, 
Very nice lib with the system of navbar, thanks !
I noticed that the content filled into value, can only be stringed and are placed inside a paragraph element.
Is there a way to place a video as a content or another component to display in the accordion ?
Thanks for your help.

**Comment by gerasimvol** [comment]
@tpoussard absolutely! You can pass item as `scoped-slot`
I have updated README and you can check demo in `/demo` folder

https://github.com/gerasimvol/vue-faq-accordion#-slots
